import { Specialist, Service, Booking, Transaction } from './types';

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'service-1',
    name: 'Limpeza de Pele Profunda',
    duration: 60,
    price: 180,
    category: 'Estética Facial',
    icon: 'Sparkles',
  },
  {
    id: 'service-2',
    name: 'Toxina Botulínica (Botox)',
    duration: 45,
    price: 950,
    category: 'Estética Facial',
    icon: 'Activity',
  },
  {
    id: 'service-3',
    name: 'Preenchimento Labial',
    duration: 60,
    price: 1200,
    category: 'Estética Facial',
    icon: 'Heart',
  },
  {
    id: 'service-4',
    name: 'Peeling Químico',
    duration: 30,
    price: 320,
    category: 'Estética Facial',
    icon: 'Flame',
  },
  {
    id: 'service-5',
    name: 'Massagem Ayurvédica',
    duration: 90,
    price: 250,
    category: 'Massoterapia',
    icon: 'Leaf',
  },
  {
    id: 'service-6',
    name: 'Facial Luminosity',
    duration: 45,
    price: 220,
    category: 'Estética Facial',
    icon: 'Sun',
  },
  {
    id: 'service-7',
    name: 'Detox Corporal',
    duration: 75,
    price: 350,
    category: 'Massoterapia',
    icon: 'Droplets',
  },
  {
    id: 'service-8',
    name: 'Hidratação Facial Diamante',
    duration: 45,
    price: 280,
    category: 'Estética Facial',
    icon: 'Gem',
  }
];

export const INITIAL_SPECIALISTS: Specialist[] = [
  {
    id: 'spec-1',
    name: 'Dr.ª Marina Silva',
    role: 'Esteta Facial',
    commission: 30,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=300',
    rating: 4.8,
    services: ['service-1', 'service-4', 'service-6', 'service-8'],
    active: true,
    attendanceCount: 115,
  },
  {
    id: 'spec-2',
    name: 'Dr.ª Beatriz Souza',
    role: 'Dermatologia Estética',
    commission: 35,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    services: ['service-1', 'service-2', 'service-3', 'service-4'],
    active: true,
    attendanceCount: 142,
  },
  {
    id: 'spec-3',
    name: 'Juliana Mendes',
    role: 'Terapeuta Corporal',
    commission: 40,
    avatarUrl: 'https://images.unsplash.com/photo-1622324267244-be02fc5f7919?auto=format&fit=crop&q=80&w=300',
    rating: 4.7,
    services: ['service-5', 'service-7'],
    active: true,
    attendanceCount: 98,
  },
  {
    id: 'spec-4',
    name: 'Dr.ª Helena Rocha',
    role: 'Harmonização Facial',
    commission: 50,
    avatarUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    services: ['service-2', 'service-3', 'service-4', 'service-8'],
    active: true,
    attendanceCount: 204,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-1',
    specialistId: 'spec-1',
    specialistName: 'Dr.ª Marina Silva',
    userName: 'Clara Valente',
    userWhatsapp: '(11) 9 9876-5432',
    serviceIds: ['service-1'],
    serviceNames: ['Limpeza de Pele Profunda'],
    date: '2026-05-22',
    time: '09:00',
    status: 'confirmado',
    totalPrice: 180,
    totalDuration: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'book-2',
    specialistId: 'spec-1',
    specialistName: 'Dr.ª Marina Silva',
    userName: 'Mariana Costa',
    userWhatsapp: '(11) 9 9123-4567',
    serviceIds: ['service-3'],
    serviceNames: ['Preenchimento Labial'],
    date: '2026-05-22',
    time: '11:30',
    status: 'pendente',
    totalPrice: 1200,
    totalDuration: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'book-3',
    specialistId: 'spec-3',
    specialistName: 'Juliana Mendes',
    userName: 'Anita Borges',
    userWhatsapp: '(21) 9 8888-7777',
    serviceIds: ['service-5'],
    serviceNames: ['Massagem Ayurvédica'],
    date: '2026-05-22',
    time: '14:00',
    status: 'confirmado',
    totalPrice: 250,
    totalDuration: 90,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'trans-1',
    type: 'entrada',
    description: 'Agendamento - Clara Valente',
    amount: 180,
    date: '2026-05-22',
    category: 'Serviços',
    specialistId: 'spec-1',
    specialistName: 'Dr.ª Marina Silva',
  },
  {
    id: 'trans-2',
    type: 'entrada',
    description: 'Agendamento - Anita Borges',
    amount: 250,
    date: '2026-05-22',
    category: 'Serviços',
    specialistId: 'spec-3',
    specialistName: 'Juliana Mendes',
  },
  {
    id: 'trans-3',
    type: 'saida',
    description: 'Repositor de Agulhas e Seringas Botox',
    amount: 450,
    date: '2026-05-21',
    category: 'Materiais',
  },
  {
    id: 'trans-4',
    type: 'saida',
    description: 'Aluguel do Espaço - Competência Maio',
    amount: 3200,
    date: '2026-05-15',
    category: 'Aluguel',
  },
  {
    id: 'trans-5',
    type: 'entrada',
    description: 'Pacote Clareamento Facial Completo',
    amount: 1800,
    date: '2026-05-20',
    category: 'Serviços',
    specialistId: 'spec-2',
    specialistName: 'Dr.ª Beatriz Souza',
  },
  {
    id: 'trans-6',
    type: 'entrada',
    description: 'Venda de Creme Hidratante Alves',
    amount: 120,
    date: '2026-05-22',
    category: 'Venda de Produtos',
  }
];
