import { Specialist, Service, Booking, Transaction, DEFAULT_WEEKLY_SCHEDULE } from './types';

export const INITIAL_SERVICES: Service[] = [
  // PODOLOGIA
  {
    id: 'service-pod-1',
    name: 'Spa de Podologia Completo',
    duration: 60,
    price: 130,
    category: 'Podologia',
    icon: 'Sparkles',
  },
  {
    id: 'service-pod-2',
    name: 'Tratamento de Calosidades & Unhas Encravadas',
    duration: 45,
    price: 150,
    category: 'Podologia',
    icon: 'Heart',
  },
  // NAILS
  {
    id: 'service-nail-1',
    name: 'Alongamento em Fibra de Vidro',
    duration: 120,
    price: 190,
    category: 'Nails',
    icon: 'Gem',
  },
  {
    id: 'service-nail-2',
    name: 'Pé e Mão Completo Especial',
    duration: 60,
    price: 85,
    category: 'Nails',
    icon: 'Sparkles',
  },
  {
    id: 'service-nail-3',
    name: 'Esmaltação em Gel & Blindagem',
    duration: 45,
    price: 110,
    category: 'Nails',
    icon: 'Heart',
  },
  // CABELEIREIRA
  {
    id: 'service-hair-1',
    name: 'Corte Design & Visagismo',
    duration: 60,
    price: 150,
    category: 'Cabeleireira',
    icon: 'Scissors',
  },
  {
    id: 'service-hair-2',
    name: 'Mechas Glamour & Reconstrução',
    duration: 180,
    price: 480,
    category: 'Cabeleireira',
    icon: 'Flame',
  },
  {
    id: 'service-hair-3',
    name: 'Escova Modeladora & Hidratação',
    duration: 45,
    price: 110,
    category: 'Cabeleireira',
    icon: 'Sun',
  },
  // LASH DESIGN
  {
    id: 'service-lash-1',
    name: 'Extensão de Cílios Volume Brasileiro',
    duration: 125,
    price: 160,
    category: 'Lash Design',
    icon: 'Eye',
  },
  {
    id: 'service-lash-2',
    name: 'Lash Lifting Premium',
    duration: 60,
    price: 130,
    category: 'Lash Design',
    icon: 'Sparkles',
  }
];

// Seeded specialists have no hash; the server accepts the initial password
// "alves2026" via fallback. Replace passwords via the Equipe form to lock down.
export const INITIAL_SPECIALISTS: Specialist[] = [
  {
    id: 'spec-admin',
    name: 'Administração Alves',
    specialty: 'Gestão geral do salão',
    commission: 0,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    rating: 5,
    services: [],
    active: true,
    attendanceCount: 0,
    username: 'admin',
    roleType: 'admin',
    weeklySchedule: DEFAULT_WEEKLY_SCHEDULE,
  },
  {
    id: 'spec-1',
    name: 'Juliana Neves',
    specialty: 'Podologia Clarificadora & Spa de Alta Técnica',
    commission: 30,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    services: ['service-pod-1', 'service-pod-2'],
    active: true,
    attendanceCount: 158,
    username: 'juliana',
    roleType: 'professional',
    weeklySchedule: DEFAULT_WEEKLY_SCHEDULE,
  },
  {
    id: 'spec-2',
    name: 'Gabriela Rocha',
    specialty: 'Alongamentos Refinados, Gel & Blindagem de Unhas',
    commission: 35,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    rating: 4.8,
    services: ['service-nail-1', 'service-nail-2', 'service-nail-3'],
    active: true,
    attendanceCount: 214,
    username: 'gabriela',
    roleType: 'professional',
    weeklySchedule: DEFAULT_WEEKLY_SCHEDULE,
  },
  {
    id: 'spec-3',
    name: 'Karina Alencar',
    specialty: 'Cortes Design, Mechas Criativas & Reconstrução Capilar',
    commission: 40,
    avatarUrl: 'https://images.unsplash.com/photo-1622324267244-be02fc5f7919?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    services: ['service-hair-1', 'service-hair-2', 'service-hair-3'],
    active: true,
    attendanceCount: 187,
    username: 'karina',
    roleType: 'professional',
    weeklySchedule: DEFAULT_WEEKLY_SCHEDULE,
  },
  {
    id: 'spec-4',
    name: 'Aline Oliveira',
    specialty: 'Extensões Volume Brasileiro & Lash Lifting Premium',
    commission: 35,
    avatarUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    services: ['service-lash-1', 'service-lash-2'],
    active: true,
    attendanceCount: 230,
    username: 'aline',
    roleType: 'professional',
    weeklySchedule: DEFAULT_WEEKLY_SCHEDULE,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-1',
    specialistId: 'spec-1',
    specialistName: 'Juliana Neves',
    userName: 'Clara Valente',
    userWhatsapp: '(11) 9 9876-5432',
    serviceIds: ['service-pod-1'],
    serviceNames: ['Spa de Podologia Completo'],
    date: '2026-05-22',
    time: '09:00',
    status: 'confirmado',
    totalPrice: 130,
    totalDuration: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'book-2',
    specialistId: 'spec-4',
    specialistName: 'Aline Oliveira',
    userName: 'Mariana Costa',
    userWhatsapp: '(11) 9 9123-4567',
    serviceIds: ['service-lash-1'],
    serviceNames: ['Extensão de Cílios Volume Brasileiro'],
    date: '2026-05-22',
    time: '11:00',
    status: 'pendente',
    totalPrice: 160,
    totalDuration: 125,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'book-3',
    specialistId: 'spec-3',
    specialistName: 'Karina Alencar',
    userName: 'Anita Borges',
    userWhatsapp: '(21) 9 8888-7777',
    serviceIds: ['service-hair-3'],
    serviceNames: ['Escova Modeladora & Hidratação'],
    date: '2026-05-22',
    time: '14:00',
    status: 'confirmado',
    totalPrice: 110,
    totalDuration: 45,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'trans-1',
    type: 'entrada',
    description: 'Agendamento - Clara Valente',
    amount: 130,
    date: '2026-05-22',
    category: 'Serviços',
    specialistId: 'spec-1',
    specialistName: 'Juliana Neves',
  },
  {
    id: 'trans-2',
    type: 'entrada',
    description: 'Agendamento - Anita Borges',
    amount: 110,
    date: '2026-05-22',
    category: 'Serviços',
    specialistId: 'spec-3',
    specialistName: 'Karina Alencar',
  },
  {
    id: 'trans-3',
    type: 'saida',
    description: 'Repositor de Equipamentos de Unha & Cabeleireiro',
    amount: 250,
    date: '2026-05-21',
    category: 'Materiais',
  },
  {
    id: 'trans-4',
    type: 'saida',
    description: 'Aluguel do Espaço - Competência Maio',
    amount: 3200,
    date: '2026-05-15',
    category: 'Aluguel',
  },
  {
    id: 'trans-5',
    type: 'entrada',
    description: 'Serviço Combo Nails & Lash Premium',
    amount: 350,
    date: '2026-05-20',
    category: 'Serviços',
    specialistId: 'spec-2',
    specialistName: 'Gabriela Rocha',
  },
  {
    id: 'trans-6',
    type: 'entrada',
    description: 'Venda de Óleo Nutritivo Cutículas Alves',
    amount: 80,
    date: '2026-05-22',
    category: 'Venda de Produtos',
  }
];
